### PR TITLE
WIFI-990 prefix ap debug ports

### PR DESCRIPTION
**Pull request by brennerm**

### CODE REVIEW

**Comment by brennerm** [comment]
@rahulsharma2020 This PR implements the change you suggested in #30. Let me know if that works for you.

**Review by rahulsharma2020 — APPROVED** [review]
Nicely implemented @brennerm. Definitely easy to maintain. Thank you!
Question on testability: Were you able to test it on EKS and Minikube deployments.

**Comment by brennerm** [comment]
I've tested my changes on a CloudSDK installation running on EKS. Below you can find the diff (only had two debug ports configured).

Should we notify anyone about the change introduced with this PR?

```
tip-pr-2, tip-wlan-2-wlan-port-forwarding-gateway-service, Deployment (apps) has changed:
...
-             - name: debugport-0
+             - name: apdebugport-0
...
-             - name: debugport-1
+             - name: apdebugport-1
...
tip-pr-2, tip-wlan-2-wlan-port-forwarding-gateway-service, Service (v1) has changed:
...
-       name: debugport-0
+       name: apdebugport-0
...
-       name: debugport-1
+       name: apdebugport-1
...
tip-pr-2, tip-wlan-2-wlan-port-forwarding-gateway-service-config, ConfigMap (v1) has changed:
...
-     #!/bin/bash
...
+     #!/bin/bash
+     
...
-     sysctl -w net.ipv4.ip_local_port_range="30410    30435"
-   
+     sysctl -w net.ipv4.ip_local_port_range="30510 30511"
+     
...
-   
+     
...
-   
+     
...
-   
-   
+     
+     
...
-   
+     
...
-   
+     
...
-   
-   
+     
+     
...
-   
+     
...
-   
+     
...

```

**Comment by brennerm** [comment]
@rahulsharma2020 ping

**Review by rahulsharma2020 — APPROVED** [review]

**Comment by rahulsharma2020** [comment]
> @rahulsharma2020 ping

Thank you for the reminder. 

For `Should we notify anyone about the change introduced with this PR?`, I would think the usual way of posting on the Slack channel would be good. Functionality wise we are still exposing the same set of ports, so users won't notice.

**Pull request merged**
